apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flask-eks-cluster
  region: us-west-2
  version: "1.36"

managedNodeGroups:
  - name: managed-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3

